In [1]:
print('안녕하세요')
print(100)

안녕하세요
100


In [3]:
# 주석 => 코드 내부에 사용, 코드로 인식하지 않음, 간단한 메모
# 변수 => 데이터를 저장(메모리: 플래시메모리, 램)하는 방식
# 변수이름(식별자) = 값(데이터: 숫자, 문자열, 논리값(True, False), 객체)
# 변수에는 데이터를 저장하고 있는 메모리의 주소값을 저장
num = 10

In [4]:
print(num)

10


In [5]:
id(num)

140724707804360

In [6]:
num+100

110

In [7]:
# 변수 = 데이터
# 데이터 => 숫자, 문자, 논리값
# 숫자 => 정수, 실수
num1 = 10
num2 = 3.14

In [10]:
print(type(num1))
print(type(num2))

<class 'int'>
<class 'float'>


In [11]:
num3 = 'hello~'

In [13]:
print(num3)
print(type(num3))

hello~
<class 'str'>


In [14]:
# 논리값 : 참, 거짓 => True, False
check1 = True
check2 = False

In [16]:
print(check1, type(check1))
print(check2, type(check2))

True <class 'bool'>
False <class 'bool'>


In [17]:
str_a = 'python'

In [19]:
str_a.upper()
# 주소값.메서드()

'PYTHON'

In [20]:
str_a = 100

In [22]:
print(str_a, type(str_a))

100 <class 'int'>


In [33]:
# 문자열 생성
# ' ', " ", ''' ''', """ """
str_1 = 'Hello!'
str_2 = "안녕하세요"
str_3 = '''
안녕하세요
반갑습니다
'''
str_4 = """
select *
from emp
where empno=10
"""

In [27]:
print(str_1, type(str_1))
print(str_2, type(str_2))
print(str_3, type(str_3))
print(str_4, type(str_4))

Hello <class 'str'>
안녕하세요 <class 'str'>

안녕하세요
반갑습니다
 <class 'str'>

select *
from emp
where empno=10
 <class 'str'>


In [ ]:
# 문자열의 연산
# 사칙연산 X => 더하기(연결)
# 곱셈 * => 반복 (몇 번 반복)
print('hello'+' python!!')
print('=' * 10)

hello python!!


In [34]:
# 함수 : 데이터 전달 => 처리(연산) => 값 반환
# 문자열의 길이 반환 : len(변수: 시퀀스 형식 데이터)
print(len(str_1))
print(len(str_2))

6
5


In [35]:
# 문자열 : 시퀀스 데이터 => 순서 있음
# 시퀀스 데이터의 데이터들의 구분 => index
# hello => ['h', 'e', 'l', 'l', 'o']
# index => 0 1 2 3 4 => 0 ~ N-1 => 0~4
str_5 = 'hello~ python!!'

In [37]:
str_5[5]

'~'

In [ ]:
# 문자열(시퀀스)의 슬라이싱
# s[시작 index : 종료 index] => 종료 index 값을 만나면 탈출
# str_5[0 : 5]
str_5[0 : 5]

'hello'

In [41]:
# 문자열 포맷팅
# 3.6 버전 이후 f"", 접두사 f 붙이고 포맷팅
user_name = '손흥민'
user_age = 30
print(f'안녕하세요! 저는 {user_name}입니다. 나이는 {user_age} 입니다.')

안녕하세요! 저는 손흥민입니다. 나이는 30 입니다.


In [42]:
print(f'내년에는 나이가 {user_age+1}살이 됩니다.')

내년에는 나이가 31살이 됩니다.


In [43]:
# 복합 대입 연산
num = 1

In [44]:
num = num + 1

In [45]:
print(num)

2


In [46]:
num += 1 # num = num + 1

In [47]:
print(num)

3


In [61]:
kor = 90
eng = 75
mat = 80
print(f'국어: {kor}')
print(f'영어: {eng}')
print(f'수학: {mat}')
print(f'총합: {kor+eng+mat}')
print(f'평균: {int((kor+eng+mat)/3)}')

국어: 90
영어: 75
수학: 80
총합: 245
평균: 81


### 연습문제 1
과목별 점수, 총점, 평균 출력
과목 : 국어, 영어, 수학

In [ ]:
# 1. 변수 선언, 초기화
kor_score = 100     # 국어 점수
eng_score = 70      # 영어 점수
math_score = 80     # 수학 점수

In [65]:
# 2. 연산 : 총점, 평균
sum_score = kor_score + eng_score + math_score
avg_score = sum_score / 3

In [68]:
# 3. 결과 출력
print(f'국어 점수: {kor_score}, 영어 점수: {eng_score}, 수학 점수: {math_score}\n총점: {sum_score}\n평균 점수: {avg_score}')

국어 점수: 100, 영어 점수: 70, 수학 점수: 80
총점: 250
평균 점수: 83.33333333333333


### 연습문제 2

In [74]:
# 성별 체크, 나이 체크
# 성별이 남성이고(and), 성인 판별(18살 이상)
# 1. 변수
gender = 'M'    # 성별: 'M' | 'F'
age = 20   

In [75]:
# 2. 남성 그리고 성인
check = gender == 'M' and age >= 18

In [76]:
print('성인 남성 체크: ', check)

성인 남성 체크:  True


### 리스트, 튜플, 딕셔너리, 집합 2025.06.10

In [7]:
# 리스트 : [] => 순서를 가지는 데이터 묶음
# index 값으로 요소들을 참조 => 0 ~ N(요소의 개수)-1
list_a = [1,2,3]
# index 0 1 2
# 요소의 개수 : 3

In [8]:
print(list_a, type(list_a))

[1, 2, 3] <class 'list'>


In [9]:
# bool(), int(), float(), str(), list()

In [10]:
# 요소의 참조 : 변수처럼 사용
list_a[2]

3

In [13]:
list_a[0] + list_a[1]   # 1 + 2

3

In [11]:
list_a[2] = 4

In [12]:
list_a

[1, 2, 4]

In [15]:
list_a[-1]  # index 마지막부터 들어간다
list_a[-2]

2

In [18]:
list_a[len(list_a) - 1] # N-1

4

In [19]:
list_b = [1,2,3,['a', 'b', 'c']]
# index : 0 1 2        3
#       : [int, int, int, list]

In [20]:
len(list_b)

4

In [25]:
print(list_b[0])
print(list_b[1])
print(list_b[2])
print(list_b[3]) # list
print(list_b[3][0], list_b[3][1], list_b[3][2])
# list를 가리키는 주소값[index]

1
2
3
['a', 'b', 'c']
a b c


In [ ]:
# 슬라이싱
list_c = [1,2,3,4,5]
#         0 1 2 3 4

In [31]:
list_c[1:4]
list_c[:4]  # list_c[0:4]
list_c[1:]  # list_c[1:5]
list_c[:]
list_c

[1, 2, 3, 4, 5]

In [32]:
# list의 연산 : + , *
list_d = [100, 200, 300]

In [37]:
list_c
list_d
list_c + list_d # 새로운 리스트 생성
list_d + list_c # 새로운 리스트 생성
list_c
list_d

[100, 200, 300]

In [38]:
# * : 리스트의 요소를 N번 반복해서 저장 => 새로운 리스트
list_d * 3

[100, 200, 300, 100, 200, 300, 100, 200, 300]

In [39]:
# 리스트에 요소(데이터) 추가 : 순서 => 마지막 인덱스 다음에 데이터를 추가
# append() : 메서드 => 리스트의 마지막에 데이터 추가
list_a = [1, 2, 3]

In [43]:
list_a.append(500)
# 객체(list)
# 객체 안에 정의되어 있는 함수 ? 메서드

In [48]:
# pop : 마지막 요소 축출 => 삭제, 값을 반환
# list_a.pop()    # SupportsIndex = -1    => 기본값을 -1로 가짐
list_a.pop(0)

1

In [49]:
list_a

[2, 3]

In [50]:
list_a = [1, 4, 9, 2, 10]

In [51]:
list_a.sort()

In [52]:
list_a

[1, 2, 4, 9, 10]

In [53]:
list_a.reverse()
list_a

[10, 9, 4, 2, 1]

In [55]:
list_a.index(4)

2

In [56]:
list_a.insert(1, 100)

In [57]:
list_a

[10, 100, 9, 4, 2, 1]

In [ ]:
list_a.extend(list_d)   # 원본 데이터 수정 => 원하지 않으면 + 처리를 하자

In [61]:
list_a

[10, 100, 9, 4, 2, 1, 100, 200, 300]

In [63]:
# tuple : list와 동일
# 단 요소(데이터) 변경 불가능 => 데이터 안전하게 유지
t_1 = ()
print(type(t_1))

<class 'tuple'>


In [ ]:
t_2 = (1, 2, 3, 4)
t_3 = 10, 20, 30, 40

In [67]:
type(t_3)

tuple

In [68]:
t_3[0]

10

In [70]:
t_3[1:3]

(20, 30)

In [ ]:
a, b, c = 1000, 2000, 3000  # 특정 함수에서 반환 데이터 tuple 타입

In [72]:
print(a, b, c)

1000 2000 3000


In [73]:
t_2 + t_3

(1, 2, 3, 4, 10, 20, 30, 40)

In [74]:
t_3 * 3

(10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40)

In [77]:
# 딕셔너리 : key : value => key 값으로 데이터를 참조
# { key1 : value1, key2 : value2, ... }
dict_1 = {}
print(type(dict_1))
print(dict_1)

<class 'dict'>
{}


In [78]:
dict_2 = {1 : 'a'}
print(dict_2)
print(type(dict_2))

{1: 'a'}
<class 'dict'>


In [79]:
# 요소값 추가 => key 정의, 값 정의
dict_2[2] = 'b'
dict_2

{1: 'a', 2: 'b'}

In [81]:
dict_2[2]

'b'

In [82]:
dict_2[3] = (1,2,3)

In [84]:
del dict_2[3]

In [85]:
dict_2

{1: 'a', 2: 'b'}

In [86]:
# 학생 : 학번, 이름, 학년, 학과
student_1 = {
    's_no' : 1111,
    's_name' : 'KING',
    'grade' : 4,
    'major' : 'COM'
}

In [87]:
student_1['grade']

4

In [88]:
player = {
    'team' : 'TO',
    'name' : 'SON',
    'number' : 7
}

In [89]:
player.keys()

dict_keys(['team', 'name', 'number'])

In [90]:
list(player.keys())

['team', 'name', 'number']

In [91]:
player.values()

dict_values(['TO', 'SON', 7])

In [92]:
list(player.values())

['TO', 'SON', 7]

In [94]:
'name' in player
'age' in player

False

In [98]:
player.items()

dict_items([('team', 'TO'), ('name', 'SON'), ('number', 7)])

In [96]:
list_temp = list(player.items())

In [97]:
list_temp

[('team', 'TO'), ('name', 'SON'), ('number', 7)]

In [99]:
player['name']

'SON'

In [ ]:
pos = player.get('pos') # 키가 없을 때 반환하지 않음 => None

In [105]:
print(pos)

None


In [106]:
pos1 = player.get('pos', 'no pos')

In [107]:
print(pos1)

no pos


In [108]:
# set : 집합 => 중복 X, 순서 X, 집합 연산 사용
s_1 = set([1,2,3,4,1,2,5])
s_1

{1, 2, 3, 4, 5}

In [110]:
set_2 = set('hello')
set_2

{'e', 'h', 'l', 'o'}

In [111]:
list_1 = list(s_1)
print(list_1)

[1, 2, 3, 4, 5]


In [112]:
set_2 = set([1,2,3,4,5,6])
set_3 = set([4,5,6,7,8,9])

In [115]:
print(set_2 & set_3)
print(set_2 | set_3)
print(set_2 - set_3)

{4, 5, 6}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{1, 2, 3}


In [ ]:
# set 에서 데이터 추가(중복 데이터 입력 X) 삭제
set_2.add(7)

In [119]:
set_2

{1, 2, 3, 4, 5, 6}

In [118]:
set_2.remove(7)

In [120]:
set_2.update([1,1,3,4,7,8])

In [121]:
set_2

{1, 2, 3, 4, 5, 6, 7, 8}

### 조건문, 반복문

In [123]:
# if : 분기 => ~ 라면, 아니라면
# 성인이라면, 성인이 아니라면
age = 25

# 성인이라면 -> 환영 메세지, 미성년 -> 킥~
if age >= 18 :
    print('환영합니다~~~')
    print('게임을 시작하세요!')
else :
    print('킥~~~')

환영합니다~~~
게임을 시작하세요!


In [124]:
# 홀수 짝수 판단 => 숫자%2 : 1->홀수, 0->짝수
num = 9

if num % 2 == 0 :
    print('짝수')
else :
    print('홀수')

홀수


In [125]:
# 양수 + => num1 > 0
# 음수 - => num1 < 0
# 0 => num1 == 0 => num1이 0보다 작지도 않고 크지도 않다

num1 = 0
if num1 > 0 :
    print('양수')
else :
    if num1 < 0 :
        print('음수')
    else :
        print(0)

0


In [128]:
if num1 > 0 :
    print('양수')
elif num1 < 0 :
    print('음수')
else :
    print(0)

음수


In [131]:
# 운전면허 시험
score = 79
check_msg = 'PASS' if score >= 80 else 'FAIL'
print(check_msg)

FAIL


In [133]:
# 기본값을 정해놓고 안 되는 것만 잡아내는 방식
check_msg = 'PASS'
if score < 80 :
    check_msg = 'FAIL'
print(check_msg)

FAIL


In [139]:
# 표준 출력 함수 => print()
# 표준 입력 함수 => input()
user_age = input('나이를 입력하세요!')
print(user_age, type(user_age), 2025-int(user_age))

100 <class 'str'> 1925


In [157]:
# 내가 짠 연습문제 코드
p_age = input('나이를 입력해 주세요.')
p_age = int(p_age)
f_msg = "무료 예방접종 대상자입니다." if p_age < 15 or p_age >= 65 else "무료 예방접종 대상자가 아닙니다."
print(f_msg)

무료 예방접종 대상자입니다.


In [149]:
if age < 15 or age >= 65 :
    print('접종 대상자')
else :
    print('접종 대상자 아님')

접종 대상자 아님


In [150]:
# 대상자가 아니라고 전제한 코드
medical_msg = '대상자 아님'

if age < 15 or age >= 65 :
    medical_msg = '대상자'

print(medical_msg)

대상자 아님


In [151]:
medical_msg = '대상자' if age < 15 or age >= 65 else '대상자 아님'
print(medical_msg)

대상자 아님


In [158]:
# 반복문 : while condition(True/False) :
# 조건식을 통해서 반복 => 탈출이 가능해야 한다!
cnt = 0

while cnt < 5 :
    cnt = cnt + 1
    print(cnt)

1
2
3
4
5


In [161]:
# 1~10 까지 출력, 홀수만 출력
cnt = 0
while cnt < 10 :
    cnt += 1 # cnt = cnt + 1
    if cnt % 2 == 1 :
        print(cnt)

1
3
5
7
9


In [162]:
cnt = 0
while cnt < 10 :
    cnt += 1
    if cnt % 2 == 0 :
        continue
    print(cnt)

1
3
5
7
9


In [163]:
list_a = [1,2,3,4,5,100,200,300]

In [164]:
for i in list_a :
    print(i)

1
2
3
4
5
100
200
300


In [166]:
list_b = [(1,2), (3,4), (5,6)]

In [167]:
for n1, n2 in list_b :
    print(n1, n2)

1 2
3 4
5 6


In [174]:
# 5명의 학생이 영어 시험 => 60점 이상 PASS 출력
# 5명의 영어점수 총점, 평균
scores = [80, 50, 70, 100, 55]
num = 0     # 학생 리스트의 일련번호
sum = 0     # 총점

for score in scores :
    # 학생의 점수를 비교해서 : PASS, FAIL
    # 리스트의 일련번호 출력 : num = num + 1
    num = num + 1
    sum = sum + score
    if score >= 60 :
        print(num, score, 'PASS')
    else :
        print(num, score, 'FAIL')
print('총점 : ', sum)
print('평균 : ', sum / len(scores))

1 80 PASS
2 50 FAIL
3 70 PASS
4 100 PASS
5 55 FAIL
총점 :  355
평균 :  71.0


In [175]:
# range 함수 : 일련 번호 생성
nums_1 = range(10)      # 0 ~ 10-1

In [177]:
for num in nums_1 :
    print(num, end = ', ')

0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 

In [178]:
for num in range (3, 8) :
    print(num, end = ' ')

3 4 5 6 7 

In [179]:
for num in range(1, 11, 2) :
    print(num, end = ' ')

1 3 5 7 9 

In [184]:
# 구구단 : 2~9단        => 2~9
# 각 단 : X 1 ~ X 9     => 1~9
for dan in range(2, 10) :
    print(f'{dan} 단')
    for i in range(1, 10) :
        print(f'{dan}X{i}={dan*i}', end = ' ')
    print()

2 단
2X1=2 2X2=4 2X3=6 2X4=8 2X5=10 2X6=12 2X7=14 2X8=16 2X9=18 
3 단
3X1=3 3X2=6 3X3=9 3X4=12 3X5=15 3X6=18 3X7=21 3X8=24 3X9=27 
4 단
4X1=4 4X2=8 4X3=12 4X4=16 4X5=20 4X6=24 4X7=28 4X8=32 4X9=36 
5 단
5X1=5 5X2=10 5X3=15 5X4=20 5X5=25 5X6=30 5X7=35 5X8=40 5X9=45 
6 단
6X1=6 6X2=12 6X3=18 6X4=24 6X5=30 6X6=36 6X7=42 6X8=48 6X9=54 
7 단
7X1=7 7X2=14 7X3=21 7X4=28 7X5=35 7X6=42 7X7=49 7X8=56 7X9=63 
8 단
8X1=8 8X2=16 8X3=24 8X4=32 8X5=40 8X6=48 8X7=56 8X8=64 8X9=72 
9 단
9X1=9 9X2=18 9X3=27 9X4=36 9X5=45 9X6=54 9X7=63 9X8=72 9X9=81 


In [185]:
# 리스트의 컴프리헨션
# [표현식 for 변수 in list if 조건식]

In [188]:
list_2 = [1,2,3,4]

# 결과 리스트
list_result = []
for num in list_2 :
    if num%2 == 1 :
        list_result.append(num*3)
print(list_result)

[3, 9]


In [189]:
list_result_2 = [num*3 for num in list_2 if num%2 == 1]
print(list_result_2)

[3, 9]


In [187]:
list_result_1 = [num*3 for num in list_2]
print(list_result_1)

[3, 6, 9, 12]


### 미니과제

In [206]:
# 특정 연도 건강검진 대상 여부 판별 및 검진 종류 확인 프로그램 작성
this_year = input('올해 연도?')
birth_year = input('태어난 연도?')

this_year = int(this_year)
birth_year = int(birth_year)

if this_year-birth_year >= 20 :
    if this_year%2 == birth_year%2 :
        if this_year-birth_year >= 40 :
            print('올해 건강검진 및 무료 암 검사 대상자입니다.')
        else :
            print('올해 건강검진 대상자입니다.')
    else :
        print('올해 건강검진 대상자가 아닙니다.')
else :
    print('건강검진 대상자가 아닙니다.')

건강검진 대상자가 아닙니다.


In [212]:
# for 문을 이용하여 1부터 10까지를 곱한 결과를 출력하는 프로그램 작성

rslt = 1
for i in range(1, 11) :
    rslt = rslt * i
print(rslt)

3628800


In [222]:
# 구구단의 짝수 단(2,4,6,8)만 출력하는 프로그램 작성
for i in range(1, 9) :
    if i%2==0 :
        print(f'{i}단')
        even_num = i
        for j in range(1, even_num + 1) :
            print(f'{even_num}X{j}={even_num*j}', end=' ')
        print()

2단
2X1=2 2X2=4 
4단
4X1=4 4X2=8 4X3=12 4X4=16 
6단
6X1=6 6X2=12 6X3=18 6X4=24 6X5=30 6X6=36 
8단
8X1=8 8X2=16 8X3=24 8X4=32 8X5=40 8X6=48 8X7=56 8X8=64 


In [225]:
# While문을 무한 루프로 구성하여 작성하는 예제
num = 1
rslt = 0
while True :
    if num%2==0 or num%3==0 :
        rslt += num
        if rslt > 1000 :
            print(rslt)
            break
    num += 1

1055


### 미니과제 답

In [ ]:
# EX3
# 검진 대상장 판별
# 20세 이상, 짝수년도에는 짝수 년생들이 대상
# 40세 이상 암 검진 대상
# 올해 년도, 태어난 년도
year = 2025
birth_year = 1985
age = year-birth_year
print(age)

if age >=20 and birth_year%2==year%2 :
    print('검진 대상자입니다.')
    if age >= 40 :
        print('암 검진 대상자입니다.')
else :
    print('검진 대상자가 아닙니다.')

In [278]:
# EX 3-1
# 1부터 100까지의 합을 구하는 프로그램
sum = 0
for i in range(1, 101) :
    #print(i, end = ",")
    sum += i
print('sum : ', sum)

sum :  5050


In [279]:
# EX 3-2
# 1부터 10까지의 곱을 구하는 프로그램
result = 1
for i in range(1, 11) :
    result *= i
print('result : ', result)

result :  3628800


In [280]:
# EX 3-3
# 구구단의 짝수단(2, 4, 6, 8)단만 출력
# 2x2, 4x4, 6x6, 8x8
for dan in range(2, 9, 2) :
    print(dan, '단')
    for num in range(1, dan+1) :
        print(dan, 'x', num, '=', dan*num, end=' ')
    print()

2 단
2 x 1 = 2 2 x 2 = 4 
4 단
4 x 1 = 4 4 x 2 = 8 4 x 3 = 12 4 x 4 = 16 
6 단
6 x 1 = 6 6 x 2 = 12 6 x 3 = 18 6 x 4 = 24 6 x 5 = 30 6 x 6 = 36 
8 단
8 x 1 = 8 8 x 2 = 16 8 x 3 = 24 8 x 4 = 32 8 x 5 = 40 8 x 6 = 48 8 x 7 = 56 8 x 8 = 64 


In [284]:
# while문의 무한 루프 사용
# 1부터 시작해서 모든 짝수와 3의 배수를 더해서
# 그 합이 언제 1000을 넘어서는지
# 1000 넘어선 값은 얼마인지

num = 1
sum = 0

while True :
    # 합의 조건식
    if num%2==0 or num%3==0 :
        sum += num
    # 탈출 조건
    if sum > 1000 :
        break
    # 증가식
    num += 1

print (f'{num}이 추가되었을 때 1000을 넘어갑니다. 1000을 넘긴 최초의 값은 {sum}입니다.')

56이 추가되었을 때 1000을 넘어갑니다. 1000을 넘긴 최초의 값은 1055입니다.


### 함수 2025.06.11

In [228]:
# 함수 : 데이터를 받고 처리(연산)하고 결과 반환하는 코드들의 묶음
#       => 호출을 통해 코드를 실행
# 중복코드를 줄일 수 있다 => 유지보수, 관리가 수월해진다!
# def 함수이름(매개변수, 매개변수, 매개변수, ...) :
#   처리작업 코드들...
#   return 값(data : 파이썬에서 제공하는 타입의 모든 데이터)

In [ ]:
# 함수 정의
# 숫자 두 개를 받아 => 매개변수 : 선택사항
# 덧셈연산을 하고   => 내부 처리 작업
# 결과 값을 반환    => 반환 값 : 선택사항
def add(n1, n2) :       # 함수 정의 : 이름, 매개변수
    result = n1 + n2    # 연산, 처리, 작업
    return result       # 결과 값 반환

In [232]:
print(type(add))

<class 'function'>


In [230]:
add(10, 20) # 호출 : 이름과 괄호()안에 매개변수가 받을 수 있는 데이터를 함께 전달

30

In [233]:
add(1, 5)

6

In [241]:
# 매개변수가 없는 함수
def alert_msg() :
    # ....
    msg = '''
    안녕하세요.
    회원님.
    반갑습니다. !!!
    '''
    return msg

In [242]:
print(alert_msg())


    안녕하세요.
    회원님.
    반갑습니다. !!!
    


In [243]:
# 매개변수는 있고, 반환값이 없는 함수
# 숫자 두 개를 받아
# 덧셈 연산의 결과를 출력하는 함수
def add_print(n1, n2) :
    result = n1 + n2
    print(f'{n1}+{n2}={n1+n2}')

In [285]:
add_print(100, 20)

100+20=120


In [245]:
result_add_print = add_print(10, 200)

10+200=210


In [246]:
print(result_add_print) # 반환 값이 없으면 None 반환

None


In [247]:
# 매개변수도 없고, 반환도 없는 함수
def display_menu() :
    menu = '''
    1. 아메리카노
    2. 라떼
    3. 에스프레소
    '''
    print(menu)

In [248]:
display_menu()


    1. 아메리카노
    2. 라떼
    3. 에스프레소
    


In [249]:
len('hello')

5

In [250]:
def sub(n1, n2) :
    return n1 - n2

In [251]:
sub(n2=3, n1=10)

7

In [254]:
print('KING', 'hello', sep = '\t', end = '\t')
print('hi~!!')

KING	hello	hi~!!


In [256]:
# 매개변수가 여러 개인데 몇 개인지 몰라 ?!
print('king')
print(1,2,3,4,5)

king
1 2 3 4 5


In [ ]:
# 매개변수에서 전달되는 숫자들(몇 개?)을
# 모두 더한 값을
# 반환하는 함수
def add_sum(*args) :    # 가변매개변수 ? 튜플로 받음
    print(type(args))
    print(args)
    sum = 0
    for num in args :
        sum += num
    return sum

In [263]:
add_sum(1,2,3,4,5,6,7,8,9,10)

<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


55

In [264]:
# 연산의 타입을 전달 받고 전달되는 숫자들을
# 연산한 결과를
# 반환하는 함수
def add_type(type, *args) :
    # add, mul
    if type=='add' :
        result = 0  # 내부에서 변수 선언됨
        for num in args :
            result += num
        return result
    elif type =='mul' :
        result = 1
        for num in args :
            result *= num
        return result
    else :
        print('사용 가능한 타입을 입력해 주세요!')

In [268]:
add_type('add', 1,2,3,4,5,6,7,8,9)
add_type('mul', 1,2,3,4)
add_type('sub', 1,2,3,4)

사용 가능한 타입을 입력해 주세요!


In [272]:
def print_args(**args) :
    print(args)
    print(type(args))
    return args

In [270]:
print_args(name='손흥민', age=20)

{'name': '손흥민', 'age': 20}
<class 'dict'>


In [271]:
player1 = {
    'name' : '손흥민',
    'age' : 20
}

In [273]:
player2 = print_args(name='메시', age='30')

{'name': '메시', 'age': '30'}
<class 'dict'>


In [274]:
print(player1)
print(player2)

{'name': '손흥민', 'age': 20}
{'name': '메시', 'age': '30'}


In [275]:
def add_mul_return(n1, n2) :
    add_result = n1 + n2
    mul_result = n1 * n2
    return (add_result, mul_result)

In [277]:
result1, result2 = add_mul_return(10, 20)  # return : 튜플 형식
print(result1, result2)

30 200


In [286]:
# 매개변수의 기본값 설정
def add2(n1=0, n2=0) :
    return n1+n2

In [289]:
add2(1)

1

In [290]:
# 이름, 나이, 성별 받아서 출력 함수
def say_hi(name, age, gender=True) :    # Gender=True => 여성
    print(f'안녕하세요. 저는 {name}입니다. 나이는 {age} 입니다.')
    if gender :
        print('여성입니다.')
    else :
        print('남성입니다.')

In [292]:
say_hi('king', 20, False)

안녕하세요. 저는 king입니다. 나이는 20 입니다.
남성입니다.


In [ ]:
# 변수의 사용 범위
a = 1
def var_test(a) :   # 지역변수 => 이름이 같은 경우 지역변수가 우선이 됨
    print('함수 내부의 a : ', a)

In [294]:
var_test(10)

함수 내부의 a :  10


In [295]:
print(a)

1


In [ ]:
def var_test2() :
    # 외부의 함수를 연산해야 하는 경우 global 키워드 사용 => 참조는 안 해도 가능
    # global 사용을 추천하진 않음
    global a
    a = a + 1
    print(a)

In [301]:
var_test2()

2


In [302]:
print(a)

2


In [304]:
# lambda 함수 => 한 줄로 간단하게 표현하는 함수 표현식
# 함수이름 = lambda arg1, arg2 ... : 연산
# 숫자 두 개를 전달받아 덧셈한 결과를 반환하는 함수
add3 = lambda n1, n2 : n1+n2

In [305]:
add3(100, 10)

110

In [306]:
type(add3)

function

In [307]:
# 내장함수 : 파이썬 설치 => 기본으로 제공하는 함수
st_names = ['king', 'cool', 'hot', 'scott']

In [309]:
# 학생들의 index 값을 함께 출력
num = 0
for name in st_names :
    print(num, name)
    num += 1

0 king
1 cool
2 hot
3 scott


In [311]:
for index, name in enumerate(st_names, start=10) :
    print(index, name)

10 king
11 cool
12 hot
13 scott


In [312]:
# filter : 필터링(매개변수로 전달되는 함수 : 요소값을 판단해서 논리값 반환)을 통해 새로운 리스트를 생성 반환
# filter(fn, itr)
def positive(l) :
    result = []
    for n in l :
        if n > 0 :
            result.append(n)
    return result

In [313]:
positive([3,1,-1,-3,0,9,10,4])

[3, 1, 9, 10, 4]

In [314]:
# filter
# 판별함수
def positive_fn(x) :
    return x > 0

In [ ]:
def pos_fn2(x) :
    return x%2==1   # True 혹은 False 나오게 하면 돼 => filter는 그래야 해

In [318]:
list(filter(pos_fn2, [3,1,-1,-3,0,9,10,4]))

[3, 1, -1, -3, 9]

In [320]:
list(filter(lambda x : x%2==1, [3,1,-1,-3,0,9,10,4]))

[3, 1, -1, -3, 9]

In [323]:
list(map(lambda x : x*2, [1,2,3,4,5]))

[2, 4, 6, 8, 10]

In [ ]:
# 파이썬의 입출력(자원)
# 표준 입출력 => input, print
# 텍스트 파일(자원) : 입출력 I/O
# 파일 단위 입출력 : open(자원경로, 모드) 모드 => r(read), w(write), a(append)
f = open('new_text.txt', 'w')
f.close()

In [330]:
f = open('new_text.txt', 'w')   # 1. 파일 오픈 : w
f.write('안녕하세요!!!')   # 2. 텍스트 쓰기
f.close()

In [ ]:
f = open('new_text.txt', 'w')
for i in range(1, 11) :
    f.write(f'{i}번째 줄 입력\n')   # \n => 하단 cell 결과에도 반영이 되어있음
f.close()

In [337]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r')   # 1. 파일 열고, Read => r
line1 = f.readline()    # 첫 번째 줄 출력 후 반환
print(line1)
line2 = f.readline()    # 두 번째 줄로 커서 이동되었기 때문에 두 번째 줄 출력
print(line2)
f.close()

1번째 줄 입력

2번째 줄 입력



In [338]:
# 파일 내용 읽어오기
f = open('new_text.txt', 'r')   # 1. 파일 열고, Read => r
while 1 :
    line = f.readline()
    if not line :   # 문자열 없으면 탈출
        break
    print(line, end=' ')

f.close()

1번째 줄 입력
 2번째 줄 입력
 3번째 줄 입력
 4번째 줄 입력
 5번째 줄 입력
 6번째 줄 입력
 7번째 줄 입력
 8번째 줄 입력
 9번째 줄 입력
 10번째 줄 입력
 

In [350]:
f = open('new_text.txt', 'r')
lines = f.readlines()
print(lines)
for line in lines :
    print(line, end=' ')
f.close()

['1번째 줄 입력\n', '2번째 줄 입력\n', '3번째 줄 입력\n', '4번째 줄 입력\n', '5번째 줄 입력\n', '6번째 줄 입력\n', '7번째 줄 입력\n', '8번째 줄 입력\n', '9번째 줄 입력\n', '10번째 줄 입력새로운 행이 추가 됩니다.새로운 행이 추가 됩니다. \n', '새로운 행16이 추가 됩니다. \n', '새로운 행17이 추가 됩니다. \n', '새로운 행18이 추가 됩니다. \n', '새로운 행19이 추가 됩니다. \n', '새로운 행20이 추가 됩니다. \n', '새로운 행16이 추가 됩니다. \n', '새로운 행17이 추가 됩니다. \n', '새로운 행18이 추가 됩니다. \n', '새로운 행19이 추가 됩니다. \n', '새로운 행20이 추가 됩니다. \n']
1번째 줄 입력
 2번째 줄 입력
 3번째 줄 입력
 4번째 줄 입력
 5번째 줄 입력
 6번째 줄 입력
 7번째 줄 입력
 8번째 줄 입력
 9번째 줄 입력
 10번째 줄 입력새로운 행이 추가 됩니다.새로운 행이 추가 됩니다. 
 새로운 행16이 추가 됩니다. 
 새로운 행17이 추가 됩니다. 
 새로운 행18이 추가 됩니다. 
 새로운 행19이 추가 됩니다. 
 새로운 행20이 추가 됩니다. 
 새로운 행16이 추가 됩니다. 
 새로운 행17이 추가 됩니다. 
 새로운 행18이 추가 됩니다. 
 새로운 행19이 추가 됩니다. 
 새로운 행20이 추가 됩니다. 
 

In [346]:
# append : 데이터 추가
f = open('new_text.txt', 'a')
f.write('새로운 행이 추가 됩니다. \n')
f.close()

In [349]:
# append : 데이터 추가
f = open('new_text.txt', 'a')
for i in range(16, 21) :
    f.write(f'새로운 행{i}이 추가 됩니다. \n')
f.close()

In [351]:
# close 생략 가능한 구현 => with
with open('new_text.txt', 'r') as file :
    lines = file.readlines()
    print(lines)

['1번째 줄 입력\n', '2번째 줄 입력\n', '3번째 줄 입력\n', '4번째 줄 입력\n', '5번째 줄 입력\n', '6번째 줄 입력\n', '7번째 줄 입력\n', '8번째 줄 입력\n', '9번째 줄 입력\n', '10번째 줄 입력새로운 행이 추가 됩니다.새로운 행이 추가 됩니다. \n', '새로운 행16이 추가 됩니다. \n', '새로운 행17이 추가 됩니다. \n', '새로운 행18이 추가 됩니다. \n', '새로운 행19이 추가 됩니다. \n', '새로운 행20이 추가 됩니다. \n', '새로운 행16이 추가 됩니다. \n', '새로운 행17이 추가 됩니다. \n', '새로운 행18이 추가 됩니다. \n', '새로운 행19이 추가 됩니다. \n', '새로운 행20이 추가 됩니다. \n']


In [ ]:
# 예외처리 : 에러 발생 시에 비정상적인 종료 막기 위한 처리
print(10/0)

In [ ]:
list_t = [1,2,3]
print(list_t[-4])

In [ ]:
userName

In [352]:
dict_t = {
    'name' : 'SON'
}

In [ ]:
dict_t['age']

In [ ]:
f = open('new_text1.txt', 'r')
f.close()

In [ ]:
add()

In [353]:
try :
    print(10/0)     # 에러 예상 위치
except :
    pass    # 파이썬은 들여쓰기하고 꼭 뭔가를 써야 하는데 쓸 게 없을 때

print('프로그램을 종료합니다.')

프로그램을 종료합니다.


In [355]:
try :
    print(10/5)     # 에러 예상 위치
except :
    print('에러가 발생했습니다. 에러에 대한 처리를 합니다.')
print('프로그램을 종료합니다.')
# 에러 => 논리적 오류
# 새로운 에러 타입 커스텀 가능

2.0
프로그램을 종료합니다.


In [ ]:
try :
    print(10/2)
    print(list_t[1])       # <=======
    print(uname)
except ZeroDivisionError as e :
    print('0으로 나누는 연산은 불가능합니다.')
    print(e)
except NameError as e :
    # print('정의되지 않은 식별자입니다.')
    print('에러가 발생했습니다.')
    print(e)
# except IndexError as e :
#     print('리스트의 index 범위에서 벗어납니다.')
#     print(e)
except :
    print('에러 발생!!!')

5.0
('team', 'TO')
정의되지 않은 식별자입니다.
name 'uname' is not defined


In [ ]:
# try : except : finally : => 에러 발생 여부와 상관 없이 실행되어야 하는 블록
try :
    print('hello')
    print(10/2)
except :
    print('error!!')
finally :
    print('!!!!!')


hello
5.0
!!!!!


In [ ]:
try :
    age = int(input('나이를 입력하세요'))
except :
    print('숫자 형식으로 입력해주세요!!!!!!')
else :
    if age > 18 :
        print('입장')
    else :
        print('불가')

숫자 형식으로 입력해주세요!!!!!!


In [4]:
# 사용자 정의 예외 타입 정의
# 논리적인 오류 발생 => 예외로 처리
# age => 음수, 500 : 논리적 오류
class MyError(Exception) :
    pass

In [ ]:
# 에러 강제 발생
raise MyError()

In [ ]:
try :
    age = int(input('나이를 입력하세요!'))
    if age < 1 or age > 200 :
        raise MyError()
except MyError :
    print('나이의 입력 범위는 1~200 까지입니다.\n 다시 입력하세요!')
except :
    print('다시 입력하세요!')
else :
    print(age)

나이의 입력 범위는 1~200 까지입니다.
 다시 입력하세요!


### 2025.06.12

In [ ]:
# 객체지향 프로그래밍 : 객체의 개념을 프로그래밍에 도입
# 객체 : 변수들, 함수들로 구성 => 메모리에 올라가 있는 상태
# 클래스 : 변수들과 함수들이 어떻게 구성되는지의 설계도 => 변수들을 정의, 함수들을 정의
# 클래스만 정의했다 => 사용 안 됨, 클래스를 이용해서 객체로 만들어야 사용 가능
# class 클래스이름 :
#   변수들과 함수들을 정의
# 클래스의 정의 => 새로운 사용자 정의 타입을 만든 것!
# 객체 생성 => 변수 = 클래스이름()          => 객체 생성 : 메모리에 주소값 반환
# 객체의 활용 => 변수.객체가_가지는_변수, 변수.객체가_가지는_함수() <= 메서드(객체가 가지는 함수)
# 클래스 정의
class Cookie :
    pass

In [4]:
# 객체 생성
c1 = Cookie()
c2 = Cookie()

In [5]:
print(id(c1), type(c1))
print(id(c2), type(c2))

2487272728656 <class '__main__.Cookie'>
2487272729296 <class '__main__.Cookie'>


In [20]:
# 사칙연산을 하는 클래스 정의
# 변수는 두 개, 함수(메서드) 4개
class FourCal :

    # 초기화(변수 선언 -> 최초 데이터를 할당) 메서드 = 생성자, 생성자함수
    # 필요한 변수들의 생성, 값을 초기화
    def __init__(self, first, second) :
        self.first = first
        self.second = second
        
    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 함
    # self => 객체 자신을 가리키는 변수(객체의 주소)
    def setdata(self, first, second) :
        self.first = first
        self.second = second
    
    # 사칙연산 함수
    def add(self) :
        return self.first + self.second
    def sub(self) :
        return self.first - self.second
    def mul(self) :
        return self.first * self.second
    def div(self) :
        return self.first / self.second

In [8]:
cal_1 = FourCal()

In [10]:
type(cal_1)

__main__.FourCal

In [11]:
cal_1.setdata(10, 20)

In [12]:
print(cal_1.first, cal_1.second)

10 20


In [13]:
cal_2 = FourCal()

In [15]:
cal_2.first

AttributeError: 'FourCal' object has no attribute 'first'

In [16]:
cal_3 = FourCal()

TypeError: FourCal.__init__() missing 2 required positional arguments: 'first' and 'second'

In [17]:
cal_4 = FourCal(100, 200)

In [19]:
cal_4.first
cal_4.second

200

In [21]:
cal_5 = FourCal(10, 7)

In [26]:
print(cal_5.first, cal_5.second)
print(cal_5.add())
print(cal_5.sub())
print(cal_5.mul())
print(cal_5.div())

10 7
17
3
70
1.4285714285714286


In [74]:
# 학생 class 생성 => 객체 생성
# 변수 : 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능 : 전체 데이터 출력하는 메서드 (이름, 학번, 총점, 평균) 
#       총점 계산
#       평균 계산
# 시뮬레이션 : 테스트 학생 데이터 생성 -> 결과 출력
class st_practice :
    def __init__(self, num, name, kor, eng, math):
        self.num = num
        self.name = name
        self.kor = kor
        self.eng = eng
        self.math = math

    def sum (self) :
        return self.kor+self.eng+self.math
    
    def avg (self) :
        return self.sum()/3
    
    def printdata(self) :
        # print(self.num, self.name, self.sum(), self.avg())
        print('성적표', '-'*20)
        print(f'이름: {self.name} ({self.num})')
        print('국어 :', self.kor)
        print('영어 :', self.eng)
        print('수학 :', self.math)
        print('총점 :', self.sum())
        print('평균 :', self.avg())

In [75]:
test_st = st_practice(815, '테스트', 100, 90, 80)
test_st.printdata()

성적표 --------------------
이름: 테스트 (815)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0


In [93]:
# 강사님 코드
class Student:
    # 데이터 초기화
    def __init__(self, name, sno, k_score, e_score, m_score):
        self.s_name = name
        self.s_no = sno
        self.k_score = k_score
        self.e_score = e_score
        self.m_score = m_score

    def sum(self) :
        return self.k_score + self.e_score + self.m_score
    
    def avg(self) :
        return self.sum()/3

    def print_result(self) :
        print('성적표', '-'*20)
        print(f'이름: {self.s_name} ({self.s_no})')
        print('국어 :', self.k_score)
        print('영어 :', self.e_score)
        print('수학 :', self.m_score)
        print('총점 :', self.sum())
        print('평균 :', self.avg())

In [86]:
st_1 = Student()

TypeError: Student.__init__() missing 5 required positional arguments: 'name', 'sno', 'k_score', 'e_score', and 'm_score'

In [87]:
type(st_1)

NameError: name 'st_1' is not defined

In [94]:
st_2 = Student('손흥민', 12345, 80, 70, 50)

In [95]:
st_2.print_result()

성적표 --------------------
이름: 손흥민 (12345)
국어 : 80
영어 : 70
수학 : 50
총점 : 200
평균 : 66.66666666666667


In [77]:
students = [
    st_practice(815, '테스트1', 100, 90, 80),
    st_practice(816, '테스트2', 100, 90, 80),
    st_practice(817, '테스트3', 100, 90, 80),
    st_practice(818, '테스트4', 100, 90, 80),
    st_practice(819, '테스트5', 100, 90, 80),
]

In [78]:
for s in students :
    s.printdata()

성적표 --------------------
이름: 테스트1 (815)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0
성적표 --------------------
이름: 테스트2 (816)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0
성적표 --------------------
이름: 테스트3 (817)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0
성적표 --------------------
이름: 테스트4 (818)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0
성적표 --------------------
이름: 테스트5 (819)
국어 : 100
영어 : 90
수학 : 80
총점 : 270
평균 : 90.0


In [ ]:
# 클래스의 상속 : 새로운 클래스를 만들 때 기존의 클래스의 멤버들을 받아서 생성하는 방법
# class 클래스이름(부모클래스)
class MoreFourCal(FourCal) :
    def pow(self) :
        return self.first**self.second

    def div(self) :
        if self.second == 0 :
            return 0
        else :
            return self.first/self.second

In [82]:
mcal_1 = MoreFourCal(100, 8)

In [86]:
print(mcal_1.add())
print(mcal_1.sub())
print(mcal_1.mul())
print(mcal_1.div())

108
92
800
12.5


In [97]:
mcal_2 = MoreFourCal(100, 0)

In [98]:
print(mcal_2.add())
print(mcal_2.sub())
print(mcal_2.div())
print(mcal_2.pow())

100
100
0
1


### 표준 모듈

In [101]:
import datetime

In [102]:
# 전부 대문자 변수 ? 상수
day1 = datetime.date(2025, 6, 12)

In [104]:
print(day1)

2025-06-12


In [105]:
day2 = datetime.date(2025, 1, 1)

In [ ]:
print(day1-day2)    # 162일이 지났음

162 days, 0:00:00


In [1]:
import time

In [2]:
time.time()

1749711431.590531

In [ ]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=6, tm_mday=12, tm_hour=15, tm_min=57, tm_sec=22, tm_wday=3, tm_yday=163, tm_isdst=0)

In [4]:
time.ctime()

'Thu Jun 12 15:58:57 2025'

In [5]:
import random

In [10]:
random.random()     # 0.00000000 <= R < 1

0.2576249752303731

In [22]:
random.randint(60, 100)

90

In [26]:
list_score = []
for s in range(0, 10) :
    list_score.append(random.randint(60, 100))

print(list_score)

[79, 91, 73, 83, 88, 85, 74, 86, 90, 85]


In [34]:
random.choice([1,2,3,4,5,6,7,8])

6

In [35]:
random.sample([1,2,3,4,5,6,7,8,9], 5)

[3, 7, 8, 1, 9]

In [36]:
import os

In [83]:
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\User\\AppData\\Roaming',
        'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_10672_LBQYLYHOHETCCTLW',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'DESKTOP-SA342QM',
        'COMSPEC': 'C:\\Windows\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'EFC_1272': '1',
        'ELECTRON_RUN_AS_NODE': '1',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\User',
        'JPY_INTERRUPT_EVENT': '1892',
        'LOCALAPPDATA': 'C:\\Users\\User\\AppData\\Local',
        'LOGONSERVER': '\\\\DESKTOP-SA342QM',
        'NUMBER_OF_PROCESSORS': '12',
        'ONEDRIVE': 'C:\\Users\\User\\OneDrive',
        'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined',
        'OS': 'Windows_NT',
     

In [37]:
os.chdir('c:\\windows')

In [40]:
os.getcwd()

'C:\\Project\\py_project'

In [39]:
os.chdir('C:\\Project\\py_project')

In [41]:
os.mkdir('test')

In [42]:
os.rmdir('test')

In [43]:
import json

In [44]:
with open('data.json', 'r', encoding='UTF8') as f :
    data = json.load(f)

In [46]:
print(data, type(data))

{'name': '손흥민', 'age': 30, 'Number': 7} <class 'dict'>


In [47]:
json_str_data = json.dumps(data)

In [ ]:
print(json_str_data, type(json_str_data))

{"name": "\uc190\ud765\ubbfc", "age": 30, "Number": 7} <class 'str'>


In [51]:
import numpy as np

In [52]:
arr = np.array([1,2,3,4,5])

In [54]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [55]:
arr + 10

array([11, 12, 13, 14, 15])

In [57]:
# 배열의 생성
# 0으로 채워지는 배열 생성
zeros = np.zeros((1,3))
print(zeros)

[[0. 0. 0.]]


In [60]:
# 1로 채우는 배열
ones = np.ones((5,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 일련번호 생성되는 배열
# 0~10 사이의 숫자를 2씩 간격으로 생성
# seq_1 = np.arange(0, 10, 2)
seq_1 = np.arange(1, 10, 3)
print(seq_1)

[1 4 7]


In [ ]:
# 지정된 범위 안에서 동일한 간격으로 숫잘르 생성
# 0~1 5개로 구분
linspace = np.linspace(1, 10, 4)
print(linspace)

[ 1.  4.  7. 10.]


In [79]:
# 배열의 속성 확인
arr1 = np.array([[1,2,3], [4,5,6]])

In [82]:
print(type(arr1))
print(arr1.shape)   # 배열의 크기 (행, 열) => (3, 3)
print(arr1.ndim)    # 배열의 차원 : 2 (Depth)
print(arr1.size)    # 요소의 개수 : 6
print(arr1.dtype)   # int64

<class 'numpy.ndarray'>
(2, 3)
2
6
int64
